2019-10-06 18:44:36,901 INFO: Microblog startup [in /home/kibet/Documents/microblog/app/__init__.py:44]
2019-10-06 18:44:50,118 ERROR: Exception on /reset_password_request [POST] [in /home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kibet/Documents/microblog/app/routes.py", line 157, in reset_password_request
    send_password_reset_email(user)
  File "/home/kibet/Documents/microblog/app/email.py", line 24, in send_password_reset_email
    user=user, token=token))
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/kibet/Documents/microblog/app/templates/email/reset_password.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/kibet/Documents/microblog/app/templates/base.html", line 32, in top-level template code
    {% block content %} {% endblock %}
  File "/home/kibet/Documents/microblog/app/templates/email/reset_password.html", line 7, in block "content"
    {{ form.hidden_tag() }}
  File "/home/kibet/Documents/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2019-10-06 18:47:48,315 INFO: Microblog startup [in /home/kibet/Documents/microblog/app/__init__.py:44]
